### PR TITLE
Translation update (ko)

### PR DESCRIPTION
**Pull request by araname**
This pull request contains some translation updates.

### CODE REVIEW

**Comment by araname** [comment]
I found Transifex and I close this.

**Comment by LotarProject** [comment]
You are welcome! Added in Transifex.

**Comment by araname** [comment]
Why not update Korean translation from Transifex?

**Comment by LotarProject** [comment]
Sorry the problem is my batch script was not work properly. Fixed and added the Korean translation in develop branch. Sorry :P 

Joseph

**Pull request closed without merging**
