### PR TITLE
Upgrade library simple_html_dom to 1.8.1

### PR DESCRIPTION
**Pull request by GergoLadi**
This PR upgrades the library _simple_html_dom_ to version 1.8.1 from 1.5, making the theme compatible with PHP 7.3. _tpl_functions.php_ is also updated to work with the new version of the library.

### CODE REVIEW

**Comment by LotarProject** [comment]
Merged. Thanks!!! ;)

**Comment by AmritasyaPutra** [comment]
Should I use the develop branch to obtain this fix or a roll out in the master branch is due anytime near?

**Comment by AmritasyaPutra** [comment]
I was checking commits, is Bootstrap 4 also in the plans for next release?

**Comment by LotarProject** [comment]
@AmritasyaPutra The v2019-05-22 release (issued few days ago) have the new version of Simple HTML DOM with Bootstrap v3 version.

The Bootstrap v4 porting will be published in Q3 / Q4 in a separated testing/preview branch.

Thanks!
Joseph

**Comment by AmritasyaPutra** [comment]
Thank you. I upgraded yesterday. The upgrade went smooth, except for the following:

PHP Warning: Invalid argument supplied for foreach() in /home/ekvastra/wiki.ekvastra.in/lib/tpl/bootstrap3/tpl/page-tools.php on line 26.

Due to this edit button has gone.

I am not so great at PHP but let me dig further. If you have a quick advise let me know.

**Comment by AmritasyaPutra** [comment]
In the course I found two bugs. For one I have opened a bug report, during rewrite showIndividualTool has been lost, this setting is not used. There is some mistake in page-tools.php but I can't express it clearly. All I can say is that if I set DokuWiki-style Page Tools then there is a problem in page-tools.php. Would you like to check this further?

**Pull request merged**
